# random normal timings
 
 Load libraries and functions
 
```{r}
library(myFunctions)
library(microbenchmark)
library(mvtnorm)
library(mvnfast)
source('~/functions/rMVN.R')
```

## Simulate data

```{r}
mu <- rnorm(200)
D <- as.matrix(dist(1:200))
Sig <- exp(-D)
y <- rnorm(200)
```

## Run bencmarks on simulating a multivariate normal

```{r}
print(microbenchmark(mvrnormArma(100, mu, Sig),
               rmvnorm(100, mu, Sig),
               rmvn(100, mu, Sig),
               times = 100L))

layout(matrix(1:3, 1, 3))
hist(mvrnormArma(100, mu, Sig))
hist(rmvnorm(100, mu, Sig))
hist(rmvn(100, mu, Sig))
```

## Run bencmarks on simulating a full conditional draw

```{r}
print(microbenchmark(rMVN(chol(Sig), mu),
               rMVNArma(Sig, mu),
               times = 100L))

layout(matrix(1:2, 1, 2))
hist(rMVN(chol(Sig), mu))
hist(rMVNArma(Sig, mu))
```

## Compare mvnfast random normal to rMVN random normal

```{r}
microbenchmark(rMVNArma(Sig, mu),
               rmvn(1, solve(Sig) %*% mu, solve(Sig)))
               
            

```

## Run benchmarks on density evaluation

```{r}
microbenchmark(dMVNorm(y, mu, Sig),
               dmvn(y, mu, Sig, log = TRUE)) 

```
